---
 - hosts: all
   tasks:
   - name: Clone a github repository
     git:
       repo: https://github.com/moshedavidrosenblum/bootcamp-app.git
       dest: /home/moshe/bootcamp
       clone: yes
       update: yes
